### PR TITLE
Chris postgre sql

### PR DESCRIPTION
**Pull request by Cristo12345**
Fixed errors on Model files and created an early draft of a Users seed file in Seeders folder

### CODE REVIEW

**Comment by ChibiKev** [comment]
Does the seeder have to be outside? and not inside the API? Because you just created an extra file for config.

**Comment by Cristo12345** [comment]
Well for best practice all the DB stuff (seeders, models, etc) should be outside in the main project directory. 

I used the Sequelize CLI so it created the 'Config', 'Migrations', and 'Seeders' folders there automatically. The new 'Config' folder can be deleted.

**Comment by ChibiKev** [comment]
I feel like it's best to leave it inside the API. This is mainly to avoid confusion between the front end and backend. Don't want it to be too messy.

**Comment by Cristo12345** [comment]
Just fixed it up, still working

**Comment by JackyLiu97** [comment]
This looks good.

**Comment by ChibiKev** [comment]
New Pull Request has been made as substitute.

**Pull request closed without merging**
